### ISSUE TITLE
Dependencies on BBQ and Protocol

### ISSUE THREAD

**Issue by StanKocken** [openid/OpenYOLO-Android#113]
With the version 0.1.1, the pom file provided the dependencies, it's not the case anymore on 0.2. 
That means a "client" will need to include `openyolo-api:0.2.0`, but also `bbq:0.2.0`, `openyolo-protocol:0.2.0`, `support-annotations`… 
Any reason why we got rid of this?

OpenYolo API 0.2.0:

    <?xml version="1.0" encoding="UTF-8"?>
    <project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <modelVersion>4.0.0</modelVersion>
      <groupId>org.openyolo</groupId>
      <artifactId>openyolo-api</artifactId>
      <version>0.2.0</version>
      <packaging>aar</packaging>
      <name>OpenYOLO for Android Client API</name>
      <url>https://github.com/openid/OpenYOLO-Android</url>
      <licenses>
        <license>
          <name>The Apache Software License, Version 2.0</name>
          <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
          <distribution>repo</distribution>
        </license>
      </licenses>
      <developers>
        <developer>
          <id>iainmcgin</id>
          <name>Iain McGinniss</name>
          <email>iainmcgin@google.com</email>
        </developer>
      </developers>
      <scm>
        <connection>https://github.com/openid/OpenYOLO-Android.git</connection>
        <developerConnection>https://github.com/openid/OpenYOLO-Android.git</developerConnection>
        <url>https://github.com/openid/OpenYOLO-Android</url>
      </scm>
    </project>

OpenYolo API 0.1.1:

    <?xml version="1.0" encoding="UTF-8"?>
    <project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <modelVersion>4.0.0</modelVersion>
      <groupId>org.openyolo</groupId>
      <artifactId>openyolo-api</artifactId>
      <version>0.1.1</version>
      <packaging>aar</packaging>
      <name>OpenYOLO for Android Client API</name>
      <url>https://github.com/openid/OpenYOLO-Android</url>
      <licenses>
        <license>
          <name>The Apache Software License, Version 2.0</name>
          <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
          <distribution>repo</distribution>
        </license>
      </licenses>
      <developers>
        <developer>
          <id>iainmcgin</id>
          <name>Iain McGinniss</name>
          <email>iainmcgin@google.com</email>
        </developer>
      </developers>
      <scm>
        <connection>https://github.com/openid/OpenYOLO-Android.git</connection>
        <developerConnection>https://github.com/openid/OpenYOLO-Android.git</developerConnection>
        <url>https://github.com/openid/OpenYOLO-Android</url>
      </scm>
      <dependencies>
        <dependency>
          <groupId>org.openyolo</groupId>
          <artifactId>bbq</artifactId>
          <version>0.1.1</version>
          <scope>compile</scope>
        </dependency>
        <dependency>
          <groupId>org.openyolo</groupId>
          <artifactId>openyolo-protocol</artifactId>
          <version>0.1.1</version>
          <scope>compile</scope>
        </dependency>
        <dependency>
          <groupId>com.android.support</groupId>
          <artifactId>support-annotations</artifactId>
          <version>25.3.1</version>
          <scope>compile</scope>
        </dependency>
        <dependency>
          <groupId>com.android.support</groupId>
          <artifactId>appcompat-v7</artifactId>
          <version>25.3.1</version>
          <scope>compile</scope>
        </dependency>
        <dependency>
          <groupId>com.android.support</groupId>
          <artifactId>support-vector-drawable</artifactId>
          <version>25.3.1</version>
          <scope>compile</scope>
        </dependency>
        <dependency>
          <groupId>org.hamcrest</groupId>
          <artifactId>hamcrest-core</artifactId>
          <version>1.3</version>
          <scope>compile</scope>
        </dependency>
        <dependency>
          <groupId>org.valid4j</groupId>
          <artifactId>valid4j</artifactId>
          <version>0.5.0</version>
          <scope>compile</scope>
        </dependency>
      </dependencies>
    </project>

**Comment by dxslly** [comment]
I noticed this yesterday as well. 

> Any reason why we got rid of this?

No, this was not intentional. We definitely want these dependencies included to allow clients to only depend on ```openyolo-api:x.y.z```.  I am not sure what the cause is yet, but will work on this today and try to get a fix in and re-release.

**Comment by iainmcgin** [comment]
I think this has probably been a side-effect of the changes I made to try and make our POM compatible with upload to Maven Central, where I had to specify the POM more explicitly. In doing so, it seems that I dropped the dependencies. David has a fix in the works and is testing it now.

**Comment by nerdyverde** [comment]
Now that this has been closed, do we have any plans to push an updated release to jcenter?

**Comment by iainmcgin** [comment]
Yeah, David's creating a 0.2.1 release.

**Comment by dxslly** [comment]
I am planning to cut the release once Iain's done with https://github.com/openid/OpenYOLO-Android/issues/99, continuing the current pattern of releasing from the master branch.

**Comment by nerdyverde** [comment]
Makes sense to me!
