### ISSUE TITLE
Planning for client library security bugs

### ISSUE THREAD

**Issue by iainmcgin** [openid/OpenYOLO-Android#12]
Based on our own (Google's) internal security guidelines, we should treat security bugs in client code as an inevitability and plan accordingly. When shipping our code as AARs that is compiled into client apps, it is infeasible to "remote update" the client library, without introducing a whole host of other possible security threats to integrators of the library.

My proposal for dealing with this situation is as follows:

1. Integrate a "kill switch" into the client library. This operates by retrieving a configuration file from an OpenID Foundation controlled domain, e.g. "www.openyolo.org". This configuration file will contain a blacklist of client library versions for which we have found security bugs. If the client library matches any of these versions, it switches to a "no-op" mode of operation where all requests fail, as though there were no credential providers on the device.

2. Set up an "openyolo-security-announce" mailing list where we can broadcast the inclusion of versions in the blacklist, and notify users of the library to update their apps with patched versions of the library as appropriate.

The technical details of implementing the kill switch are still a little unclear to me, I _believe_ we should be able to retain the client library version by using a custom [BuildConfig](http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-BuildConfig) field, though I will need to experiment with that.

It is also possible that users of the library won't like having a dependency on an external configuration file that can disable functionality in this way. So, we may need to make this opt-out, but with glaring security warnings about doing so. Those who opt out would have to be extra vigilant about monitoring the announce list and updating their apps.

Thoughts?

**Comment by tikurahul** [comment]
You could do something like this:

```gradle
android {
    ...
    buildTypes {
        debug {
            buildConfigField "String", "CLIENT_VERSION", $ext.versionNumber
        }
        ...
    }    
}
```

And use this from the client library to check for blacklisted versions.

**Comment by iainmcgin** [comment]
Yeah, I can even inject the build version using grgit, which I already use to name the output files: https://github.com/openid/OpenYOLO-Android/blob/master/build.gradle#L22

**Comment by iainmcgin** [comment]
ClientVersion added to spec and API.
