### ISSUE TITLE
Gradle Error when following the getting started guide when using Android Studio 2.x

### ISSUE THREAD

**Issue by dxslly** [openid/OpenYOLO-Android#130]
Our libraries depend a couple 26.x.y version of the support library (e.g. ```com.android.support:appcompat-v7:26.0.2```.)  AFAICT these versions are no longer served via the Android Studio's SDK Manager and instead can be retrieved by adding the Google maven repository.  The getting started guide should be updated to include this.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
