### ISSUE TITLE
Proposal: Relax validation to allow Credential Providers to recover from malformed requests

### ISSUE THREAD

**Issue by dxslly** [openid/OpenYOLO-Android#14]
### Background
Builder classes use Valid4j's require API which throws Errors when it's validation conditions are not met.

### Motivation
While this is allows would be fine for client implementations which should only be using constant values when constructing builders this puts credential providers in the position where they must catch Errors to prevent malformed requests from crashing their application.

### Proposal
Relax our validation to allow credential providers to recover from malformed requests without catching Errors. Switching to throwing run-time exceptions and catching them in our SPI base classes allows for the best of both worlds.

**Comment by nerdyverde** [comment]
I am definitely in favour of this change. I encountered exactly this kind of crashing the other day when I updated the client code with the authentication domain changes, but forgot to update the provider side of things. It was entirely my fault and I quickly realized what I'd done, but it made me painfully aware that a malformed request could crash the provider.
