### ISSUE TITLE
Feedback on demo app

### ISSUE THREAD

**Issue by riyaz** [openid/OpenYOLO-Android#144]
Well written demo app with recent best practices however when I wants to see a sample piece to integrate with my app or how it works having these extra bells and whistles is deviating from my main intention.

**Comment by dxslly** [comment]
Hi Riyaz, thanks for the feedback. I think you make a good point. For the moment I would recommend taking a look at the [getting started guide](https://github.com/openid/OpenYOLO-Android/tree/master/api).

Have you seen it? I would love your feedback to ensure it can help with this issue and is easily discoverable.

**Comment by riyaz** [comment]
Yes, library flow itself is simple so integration is easy used this too as ref https://blog.agilebits.com/2017/10/26/integrate-1password-into-your-android-apps/

Still couldn't understand hint flow, where it will be used, how it will be used?

Also, right now works well with 1password not sure how to test with Google SmartLock, I use Android O and SmartLock is enabled, but using 1password as auto fill service not sure that matters, but OpenYOLO should be independent of auto fill I suppose.

**Comment by StanKocken** [comment]
@riyaz the hint flow would be used during the signup process. You usually require an Email, a password, maybe a name… With the hint flow the providers will be able to give most of them.

And I agree with the sample app, we should have something well simpler to demo the usage, we will see what we can do.

**Comment by StanKocken** [comment]
I talked briefly with some others contributors of this repository, I will work on a very basic login/password application so it will be easier to jump on it and then close this ticket.

**Comment by StanKocken** [comment]
A new demo app, way simpler, has been added to the repository to address this issue.
