### ISSUE TITLE
Library uses Java 8 which makes integration difficult 

### ISSUE THREAD

**Issue by riyaz** [openid/OpenYOLO-Android#145]
When I tried to integrate lib build failed since OpenYOLO uses Java 8, to use Java 8 I need to migrate my app to Gradle 3.0 plugin which has its own setup process, maybe bit relaxed requirement of Java is good for easy integration.

**Comment by dxslly** [comment]
Thanks for pointing this out! I will try and new release out soon that will support 1.7+. Based on some quick  research that seems the lowest commonly used version, but if anyone knows differently please comment :)

**Comment by iainmcgin** [comment]
I wouldn't rush to change this. The 3.x build plugins are now stable, and Java 8 is here to stay.

**Comment by dxslly** [comment]
> I wouldn't rush to change this. The 3.x build plugins are now stable, and Java 8 is here to stay.
Given that it is a small change to our source code and can reduce the required work for a developer to integrate I think it is worth getting in asap. I am also concerned that this could be a blocker for some codebases where the upgrading to 3.x could be non-trival (e.g. Fennec).

**Comment by dxslly** [comment]
Done, the next release will support 1.7+.
