### ISSUE TITLE
Proguard exclusion is too broad

### ISSUE THREAD

**Issue by riyaz** [openid/OpenYOLO-Android#147]
src - https://github.com/openid/OpenYOLO-Android/blob/master/api/proguard-rules.txt

isn't this too broad?

`-keep class org.hamcrest.** { *; }`

**Comment by iainmcgin** [comment]
It is, but we also only depend on hamcrest-core rather than the full library, so the impact is fairly small. If you have a suggestion for a narrower keep rule we'd be happy to accept a PR.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
