### ISSUE TITLE
Demo app is not working as intended

### ISSUE THREAD

**Issue by riyaz** [openid/OpenYOLO-Android#148]
1. install the app
2. press back
3. enter email id and press tick button -> nothing happens

Flow exits below, i.e no password, but no password filed, even error message password too short is not displayed

`
if (userPassword.length() < MIN_PASSWORD_LENGTH) {
            passwordError.set(getResourceString(R.string.error_password_too_short));
            return;
        }
`

This change makes the demo workable 

<img width="1342" alt="screen shot 2017-10-28 at 9 31 07 pm" src="https://user-images.githubusercontent.com/22842/32136220-d4ebf130-bc27-11e7-9635-16f4bc28353d.png">

**Comment by iainmcgin** [comment]
Apologies for this Riyaz, I have a pending PR from last week which fixes a number of small issues in the demo app, this one included. I'll get it out for review and merged ASAP.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
