### ISSUE TITLE
Test app OpenYOLO Get credential button not working

### ISSUE THREAD

**Issue by nikz-dev** [openid/OpenYOLO-Android#155]
Steps to reproduce issue :
Run test app & select Retrieve page
select openyolo://email
Now click on Get Credential button
Some times credential providers are available but most of the time providers are not shown. After debug the Barbican I found that result sent from Barbican, but UI is not updated on testapp OpenYOLO ends. I also tested on Simplest but "I have an account option" also not working as expected. No provider available after click on "I have an account option" in simplest. Tested on Android 8.1 Nexus 5X.

**Comment by timcappalli** [comment]
This repo is being archived. Closing issue.
