### ISSUE TITLE
Proposal: Make it very obvious to clients OpenYOLO is not production ready

### ISSUE THREAD

**Issue by dxslly** [openid/OpenYOLO-Android#19]
The motivation is to avoid forming ill first impressions in the eyes of potential clients integrating. Until it decided that OpenYOLO is production ready I believe we should put a loud barrier in their way. For example (if possible) we could modify the client library in such a way that it requires the developer to flip a consent bit as a precondition for compilation.

**Comment by iainmcgin** [comment]
I don't know if I want to put anything into the library itself that makes it more difficult to use, as that has other developer experience issues. We could simply make it clear in each of our provider implementations that this is a alpha/beta product, and restrict requests to a whitelist of approved requesters.

**Comment by iainmcgin** [comment]
Decision - we won't do this, as we are actually approaching the point where the library _will_ be usable for production. No point adding code we will remove in a few weeks.
