### ISSUE TITLE
Use spec draft 3 underscore-delimited forms of proto fields

### ISSUE THREAD

**Issue by iainmcgin** [openid/OpenYOLO-Android#34]
We are currently using camel case field names (from spec draft 2). Change the protos to spec draft 3 form.

**Comment by dxslly** [comment]
Just noticed CredentialRetrieveBbqResponse need to be updated:

```
message CredentialRetrieveBbqResponse {
    bytes retrieveIntent = 1;
    map<string, bytes> additionalProps = 2;
}
```
