### ISSUE TITLE
Introduce delete operation to match spec draft 3

### ISSUE THREAD

**Issue by iainmcgin** [openid/OpenYOLO-Android#35]
Delete was specified as part of spec draft 3.

- Add protocol buffers
- Implement CredentialDeleteRequest / CredentialDeleteResponse validating wrappers.
- Follow pattern in CredentialClient to expose save operation.
- Add to test app.
- Add support to demo provider.

**Comment by dxslly** [comment]
Looks like this has already been completed. Closing for now.
