### ISSUE TITLE
Bug: protobuf.gradle makeExecutable throws unsupported operation for Windows

### ISSUE THREAD

**Issue by dxslly** [openid/OpenYOLO-Android#41]
protobuf.gradle#makeExecutable's Files.setPosixFilePermissions appears to not be supported on Windows.

```
def makeExecutable = { file ->
    Files.setPosixFilePermissions(
            file.toPath(),
            [
                    PosixFilePermission.OWNER_EXECUTE,
                    PosixFilePermission.GROUP_EXECUTE
            ].toSet())
}
```

**Comment by iainmcgin** [comment]
Well, this only matters for development. Fair enough though, there are windows workarounds and it might not even be necessary to set an execute bit on windows. Are you in a position to test and fix?
