### ISSUE TITLE
Only use the first Signature of apps for identification purposes

### ISSUE THREAD

**Issue by iainmcgin** [openid/OpenYOLO-Android#51]
The purpose of multiple Signatures attached to an Android app is poorly defined, both as to when multiple signatures can be present, and how these should be interpreted:

- Does the order matter?
- If an app is signed with A, or with A _and_ B, should it be considered the same app?

In practice, the Play Store only allows a single signature. The current Smart Lock for Passwords implementation makes this assumption, and therefore only uses the first signature for the app's identity. We should formalize this within the spec and implementation.

**Comment by dxslly** [comment]
Given all these unknowns I believe we must also enforce that exactly one signature is present.
