### ISSUE TITLE
Cannot access com.google.protobuf 

### ISSUE THREAD

**Issue by StanKocken** [openid/OpenYOLO-Android#62]
On the demo app Barbican, I have the class `CredentialQueryReceiver` which contains:

        if (credentialsFound) {
            Intent retrieveIntent = RetrieveCredentialActivity.createIntent(context, request);
            CredentialRetrieveBbqResponse response =
                    CredentialRetrieveBbqResponse.newBuilder()
                            .setRetrieveIntent(IntentUtil.toByteString(retrieveIntent))
                            .build();
            responseBytes = response.toByteArray();
        }

This is working fine with the OpenYolo project demo apps.
But on my side I have the following error:

![screen shot 2017-05-26 at 18 05 00](https://cloud.githubusercontent.com/assets/2204411/26502645/dbaa564c-423d-11e7-8c0a-99eb430aa383.png)

Any idea why and how to fix it?

**Comment by nerdyverde** [comment]
Hey Stan,

I was having a similar issue when incorporating the latest changes from the OpenYOLO repo. Iain was kind enough to point out that I probably needed to add

compile 'com.google.protobuf:protobuf-lite:3.0.1'
to the app build.gradle file. Hopefully that helps you as well :)

Cheers,
Michael

**Comment by StanKocken** [comment]
Thanks Michael, that did fix my issue.
We need to modify somehow the library to include this directly.
We will see with what @iainmcgin wanted to do for JCenter.
