### ISSUE TITLE
Proposal: heuristic credential provider selection

### ISSUE THREAD

**Issue by iainmcgin** [openid/OpenYOLO-Android#7]
Currently the hint and save API methods will display a "provider selector" if more than one provider is available on the device, or if the sole installed provider is not on the known provider list. This step is frustratingly repetitive. The spec includes a description of a [proposed API](https://github.com/openid/OpenYOLO-Android/blame/master/spec/en/protecting-users.md#L119) to store a pointer to the user's preferred credential provider, which would allow bypassing this step when a preference has been set.

We are not sure exactly what release of Google Play Services we will be able to release this in, and in the interim I would like to define an improved heuristic that will minimize the impact of not having it. The heuristic would behave as follows: if there are two known providers, and one of them is Google, _use the other one_. 

The justification for this is that the Google provider is in the privileged position of being installed on the vast majority of Android devices - for most users, it is not a conscious choice to have Smart Lock for Passwords on their device. However, if a _second provider_ is installed, this is almost certainly a conscious choice: installing 1Password generally implies that you want to use that for password management, and therefore you would also want that to be used for generating and saving credentials.

This heuristic does not change the behavior of retrieve, which still uses BBQ to query credential availability in all installed providers. So, if a credential exists in Smart Lock for Passwords, this would still be presented as an option on retrieve.

We may consider generalizing this proposal to "preinstalled" vs "manually installed" providers. However, that will hopefully not be necessary, as the explicit preference API will eventually land in Play Services and provide a better solution to the problem overall.

**Comment by StanKocken** [comment]
That is a very nice proposition. Of course as one of the "other one", I can only be happy with this kind of heurestic.
Thanks for your position on it, for the benefit of the user.

**Comment by nerdyverde** [comment]
I'm a little biased as well, but very happy to see this proposed. I think this provides a very reasonable guess at the user's intent.

**Comment by iainmcgin** [comment]
Implemented.
