### ISSUE TITLE
Improve documentation for clients

### ISSUE THREAD

**Issue by dxslly** [openid/OpenYOLO-Android#86]

**Comment by dxslly** [comment]
I have added an short guide to the API module's [README](https://github.com/openid/OpenYOLO-Android/blob/master/api/README.md) and done a [documentation pass](https://github.com/openid/OpenYOLO-Android/commit/8e3d22f9db18b7b3cbfe3080f456d3c24220b5c8) over the client. My current plan is to 1) cut a new release of the API module once PR https://github.com/openid/OpenYOLO-Android/pull/94 has landed. Once done we can get some feedback on the documentation and API by 2) asking a few people unfamiliar with project to integrate it into their apps.

**Comment by iainmcgin** [comment]
#123 helps towards this goal as well, if clients wish to manually migrate to the OpenYOLO API from Smart Lock for Passwords.

**Comment by dxslly** [comment]
This issue is pretty vague. I am going to close it in favor of opening more specific documentation issues.
