### ISSUE TITLE
Add get/setStringAdditionalProperty methods to model classes

### ISSUE THREAD

**Issue by iainmcgin** [openid/OpenYOLO-Android#99]
In order to be generic and extensible, the OpenYOLO model types (Credential, etc) have additional property maps that map string keys to byte arrays. We anticipate that the most common case for usage of these additional property maps will be to map strings to strings - as such, we should add utility methods for this case on the builder and model types:

```java
class ModelType {
  // ...

  /**
   * Returns a String value for the specified additional property, if it exists. String value are expected
   * to be encoded using UTF-8.
   */
  public String getStringAdditionalProperty(
      @NonNull String additionalPropertyKey) { /* ... */ }

  public static final Builder {
    // ...

    /**
     * Adds a string valued additional property. The value is encoded using UTF-8.
     */
    public void setStringAdditionalProperty(
        @NonNull String key, 
        @Nullable String value) { /* ... */ }
  }
}

public final class AdditionalPropertiesUtil {
  /**
   * Encodes a string using UTF-8 to a byte array, for storage in an additional property map.
   * If the string is null, then null will be returned.
   */
  @Nullable
  public byte[] encodeStringValue(@Nullable String value);
}
```

**Comment by dxslly** [comment]
Another possible implementation would be to add a new datatype  (e.g.```GenericProperties```) to replace the Map<String, byte[]> representation. This would have the nice benefit of consolidating these and future changes to one class (as opposed to all protocol objects).

**Comment by iainmcgin** [comment]
Done!
